import {createClient} from '@supabase/supabase-js';
const $=id=>document.getElementById(id),cfg=window.TriadOnlineConfig;
const client=createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const agents=[{name:'레이븐',role:'돌격 오퍼레이터',color:'#d6f891'},{name:'바이퍼',role:'기동 오퍼레이터',color:'#73d9e9'},{name:'고스트',role:'정찰 오퍼레이터',color:'#ffa875'}];
const defaults={primary:'0',armor:'standard',magazine:'standard',camo:'woodland'},valid={primary:window.TriadWeapons.map(w=>String(w.id)),armor:['standard','light','heavy'],magazine:['standard','extended','quick'],camo:['woodland','urban','desert']};
const clean=k=>Object.fromEntries(Object.keys(defaults).map(key=>[key,valid[key].includes(k?.[key])?k[key]:defaults[key]]));let selected=0,user=null,kits=[clean(),clean(),clean()];
function localProfile(){try{const x=JSON.parse(localStorage.getItem('triad-career-v1'))||{};return {xp:Number.isSafeInteger(x.xp)?x.xp:0,kits:[0,1,2].map(i=>clean(x.kits?.[i]))};}catch{return {xp:0,kits:[clean(),clean(),clean()]}}}
function writeLocal(){const old=localProfile();localStorage.setItem('triad-career-v1',JSON.stringify({xp:old.xp,kits}))}
const rankFor=xp=>{const names=['훈련병','이병','일병','상병','병장','하사','중사','상사','소위'],levels=[0,200,500,1000,1800,3000,4800,7200,10000];return names[Math.max(0,levels.findLastIndex(v=>xp>=v))]};
function authValue(){return {email:$('auth-id').value.trim(),password:$('auth-password').value,nickname:$('auth-nickname').value.trim().slice(0,12)}}
async function emailLogin(){const {email,password}=authValue();$('account-status').textContent='로그인 중…';const {error}=await client.auth.signInWithPassword({email,password});$('account-status').textContent=error?'로그인 실패 · ID와 비밀번호를 확인하세요.':'로그인 완료';}
async function emailSignup(){const {email,password,nickname}=authValue();if(!nickname){$('account-status').textContent='사용할 닉네임을 입력하세요.';return}$('account-status').textContent='계정 생성 중…';const local=localProfile();const {error}=await client.auth.signUp({email,password,options:{data:{nickname,triad_xp:local.xp,triad_loadouts:local.kits}}});$('account-status').textContent=error?'가입 실패 · '+error.message:'가입 완료 · 이메일 확인 후 로그인하세요.';}
async function resetPassword(){const {email}=authValue();if(!email){$('account-status').textContent='게임 ID로 사용한 이메일을 입력하세요.';return}const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:new URL('account.html',location.href).href});$('account-status').textContent=error?'재설정 요청 실패':'게임 ID는 입력한 이메일입니다. 비밀번호 재설정 메일을 확인하세요.';}
function draw(){for(const key of Object.keys(defaults))$('cloud-'+key).value=kits[selected][key];const a=agents[selected],p=$('operator-preview');p.style.setProperty('--accent',a.color);p.querySelector('strong').textContent=a.name;p.querySelector('small').textContent=a.role;document.querySelectorAll('#operator-tabs button').forEach((b,i)=>b.classList.toggle('active',i===selected));}
$('cloud-primary').innerHTML=window.TriadWeapons.map(w=>`<option value="${w.id}">${w.name} · ${w.type}</option>`).join('');$('operator-tabs').innerHTML=agents.map((a,i)=>`<button data-i="${i}">${a.name}</button>`).join('');document.querySelectorAll('#operator-tabs button').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;draw()});for(const key of Object.keys(defaults))$('cloud-'+key).onchange=e=>{kits[selected]=clean({...kits[selected],[key]:e.target.value});$('save-state').textContent='저장되지 않은 변경'};
async function oauth(provider){$('account-status').textContent='SNS 로그인 페이지로 이동 중…';const {error}=await client.auth.signInWithOAuth({provider,options:{redirectTo:new URL('account.html',location.href).href}});if(error)$('account-status').textContent=`로그인 제공자 설정이 필요합니다: ${error.message}`;}
$('login-google').onclick=()=>oauth('google');$('login-kakao').onclick=()=>oauth('kakao');$('logout').onclick=async()=>{await client.auth.signOut();location.reload()};
$('email-login').onclick=emailLogin;$('email-signup').onclick=emailSignup;$('password-reset').onclick=resetPassword;
$('save-loadout').onclick=async()=>{if(!user)return;const button=$('save-loadout');button.disabled=true;$('save-state').textContent='계정에 저장 중…';const {data,error}=await client.auth.updateUser({data:{triad_loadouts:kits,triad_xp:localProfile().xp}});button.disabled=false;if(error){$('save-state').textContent='저장 실패 · 다시 시도'}else{user=data.user;writeLocal();$('save-state').textContent='계정과 기기에 저장 완료'}};
async function session(){const {data:{session},error}=await client.auth.getSession();if(error){$('account-status').textContent='로그인 상태를 확인하지 못했습니다.';return}user=session?.user||null;$('signed-out').hidden=!!user;$('signed-in').hidden=!user;$('locker').hidden=!user;if(!user){$('account-status').textContent='이메일 ID로 가입하거나 SNS 계정을 연동하세요.';return}localStorage.setItem('triad-account-ready','1');const meta=user.user_metadata||{},local=localProfile(),xp=Math.max(local.xp,Number.isSafeInteger(meta.triad_xp)?meta.triad_xp:0);$('profile-name').textContent=meta.nickname||meta.full_name||meta.name||'TRIAD 요원';$('profile-email').textContent=user.email||'SNS 계정';$('profile-rank').textContent=`${rankFor(xp)} · 경험치 ${xp.toLocaleString()} XP`;$('avatar').src=meta.avatar_url||'icon.svg';$('account-status').textContent='로그인 완료';const cloud=meta.triad_loadouts;if(Array.isArray(cloud)&&cloud.length===3)kits=cloud.map(clean);else kits=local.kits;localStorage.setItem('triad-career-v1',JSON.stringify({xp,kits}));if(xp>Number(meta.triad_xp||0))await client.auth.updateUser({data:{triad_xp:xp,triad_loadouts:kits}});draw()}
client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN'||event==='SIGNED_OUT')setTimeout(session,0)});draw();session();

