(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d'), mini=$('map').getContext('2d');
const input=window.TriadInput;
let difficulty='standard',hudClock=0,scoreCache='';
const levels={rookie:{accuracy:.35,damage:.3,speed:1.2},standard:{accuracy:.52,damage:.4,speed:1.55},veteran:{accuracy:.7,damage:.6,speed:1.95}};
const agents=[
 {name:'고영훈',role:'돌격수',gun:'AR-30 / 돌격소총',color:'#d6f891',hp:110,speed:2.7,mag:30,damage:25,rate:.15,reload:1.6},
 {name:'하헌민',role:'기동대',gun:'SMG-40 / 기관단총',color:'#73d9e9',hp:95,speed:3.3,mag:40,damage:18,rate:.095,reload:1.3},
 {name:'오대영',role:'명사수',gun:'DMR-12 / 지정사수소총',color:'#ffa875',hp:100,speed:2.5,mag:12,damage:48,rate:.48,reload:1.9}
];
const grid=[
'11111111111111111111',
'10000000000000000001',
'10000000000000000001',
'10002220000003330001',
'10002000000000030001',
'10000000000000000001',
'10000000111000000001',
'10000000111000000001',
'10011000000000110001',
'10011000000000110001',
'10000000000000000001',
'10000000000000000001',
'10000033000022000001',
'10000030000002000001',
'10000000000000000001',
'10000000011000000001',
'10022000011000330001',
'10000000000000000001',
'10000000000000000001',
'11111111111111111111'];
const spawnPoints=[[2.5,2.5],[17.5,17.5],[17.5,2.5],[2.5,17.5],[10.5,10.5],[10.5,3.5],[3.5,11.5]];
let selected=0, state='menu', units=[], player, elapsed=0,last=0, firing=false, flash=0,hit=0,hurt=0,step=0, muted=false,audio, frame=0;
const keys=new Set();const norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
function solid(x,y){return !grid[Math.floor(y)]||grid[Math.floor(y)][Math.floor(x)]!=='0';}
function move(u,dx,dy){const r=.22;if(!solid(u.x+dx+Math.sign(dx)*r,u.y-r)&&!solid(u.x+dx+Math.sign(dx)*r,u.y+r))u.x+=dx;if(!solid(u.x-r,u.y+dy+Math.sign(dy)*r)&&!solid(u.x+r,u.y+dy+Math.sign(dy)*r))u.y+=dy;}
function ray(x,y,a,max=35){const dx=Math.cos(a),dy=Math.sin(a);let mx=Math.floor(x),my=Math.floor(y),sx=dx<0?-1:1,sy=dy<0?-1:1,ddx=Math.abs(1/dx),ddy=Math.abs(1/dy),tx=(dx<0?x-mx:mx+1-x)*ddx,ty=(dy<0?y-my:my+1-y)*ddy,side=0,d=0;while(d<max){if(tx<ty){d=tx;tx+=ddx;mx+=sx;side=0;}else{d=ty;ty+=ddy;my+=sy;side=1;}if(!grid[my]||grid[my][mx]!=='0')return{d,side,type:Number(grid[my]?.[mx]||1),uv:side?x+dx*d:y+dy*d};}return{d:max,side:0,type:1,uv:0};}
function visible(a,b){const d=Math.hypot(a.x-b.x,a.y-b.y);return ray(a.x,a.y,Math.atan2(b.y-a.y,b.x-a.x),d+.1).d>=d-.15;}
function tone(f=130,d=.07,type='sawtooth',vol=.05){if(muted)return;try{audio ||=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,f*.25),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function resize(){const scale=Math.min(1,(input.enabled?1024:1600)/innerWidth,(input.enabled?900:1000)/innerHeight);canvas.width=Math.round(innerWidth*scale);canvas.height=Math.round(innerHeight*scale);}addEventListener('resize',resize);resize();
$('characters').innerHTML=agents.map((a,i)=>`<button class="character ${i===0?'active':''}" style="--accent:${a.color}" data-index="${i}" aria-pressed="${i===0}"><span class="number">0${i+1} / ${a.role}</span><strong>${a.name}</strong><small>${a.gun.split(' / ')[1]} · HP ${a.hp}</small><div class="bar"><i style="width:${70+i*12}%"></i></div></button>`).join('');
document.querySelectorAll('.character').forEach(b=>b.onclick=()=>{selected=+b.dataset.index;document.querySelectorAll('.character').forEach(c=>{c.classList.toggle('active',c===b);c.setAttribute('aria-pressed',String(c===b));});});
function respawn(u){const others=units.filter(v=>v!==u&&v.hp>0);const options=spawnPoints.map(p=>({p,d:others.length?Math.min(...others.map(v=>Math.hypot(v.x-p[0],v.y-p[1]))):Math.random()*10})).sort((a,b)=>b.d-a.d);[u.x,u.y]=options[0].p;u.hp=agents[u.id].hp;u.ammo=agents[u.id].mag;u.reload=0;u.cool=.6;u.safe=1.3;u.dead=0;u.way=null;u.think=0;u.a=Math.atan2(10-u.y,10-u.x);}
function lock(){if(input.enabled)return;try{const p=canvas.requestPointerLock?.();p?.catch(()=>{});}catch{}}
function start(){difficulty=$('difficulty').value;scoreCache='';resize();input.setActive(true);units=[];for(let id=0;id<3;id++){const u={id,score:0,deaths:0,x:2.5,y:2.5,hp:0,a:0,think:0};units.push(u);respawn(u);}player=units[selected];elapsed=0;flash=hit=hurt=0;keys.clear();firing=false;$('feed').innerHTML='';state='playing';$('menu').hidden=$('pause').hidden=$('result').hidden=$('footer').hidden=true;$('hud').hidden=false;document.body.classList.add('playing');$('operator').textContent=agents[selected].name+' / '+agents[selected].role;$('weapon').textContent=agents[selected].gun;tone(250,.12);lock();hud();}
function pause(){if(state!=='playing')return;state='paused';input.setActive(false);keys.clear();firing=false;$('pause').hidden=false;document.exitPointerLock?.();}
function menu(){state='menu';input.setActive(false);document.exitPointerLock?.();$('menu').hidden=$('footer').hidden=false;$('pause').hidden=$('result').hidden=$('hud').hidden=true;document.body.classList.remove('playing');keys.clear();firing=false;}
$('start').onclick=$('again').onclick=start;$('back').onclick=$('select').onclick=menu;$('resume').onclick=()=>{state='playing';input.setActive(true);$('pause').hidden=true;lock();};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';};
$('pause-button').onclick=pause;
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing')pause();});
addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Escape')pause();if(e.code==='KeyR'&&state==='playing')reload(player);});addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('mousedown',e=>{if(state==='playing'&&!input.enabled&&e.button===0){firing=true;shoot(player);if(!document.pointerLockElement)lock();}});addEventListener('mouseup',()=>firing=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
let mouseX=null;addEventListener('mousemove',e=>{if(state==='playing'&&!input.enabled&&player.hp>0){if(document.pointerLockElement)player.a+=e.movementX*.0022*input.sensitivity;else if(mouseX!==null&&e.target===canvas)player.a+=(e.clientX-mouseX)*.003*input.sensitivity;}mouseX=e.clientX;});
function reload(u){if(u.hp<=0||u.reload>0||u.ammo===agents[u.id].mag)return;u.reload=agents[u.id].reload;if(u===player)tone(420,.08,'triangle');}
function event(text){const el=document.createElement('div');el.className='event';el.textContent=text;$('feed').prepend(el);while($('feed').children.length>4)$('feed').lastChild.remove();}
function damage(target,attacker,amount){if(target.safe>0||target.hp<=0)return;target.hp=Math.max(0,target.hp-amount);if(target===player){hurt=.5;tone(65,.1,'sine');}if(target.hp===0){attacker.score++;target.deaths++;target.dead=2.5;event(`${agents[attacker.id].name} ▸ ${agents[target.id].name}`);if(attacker.score>=5)finish();}}
function shoot(u,target){const a=agents[u.id];if(u.cool>0||u.reload>0||u.hp<=0)return;if(!u.ammo){reload(u);return;}u.ammo--;u.cool=a.rate;u.safe=0;if(u===player){flash=.08;tone(u.id===2?85:140,.075);const targets=units.filter(v=>v!==u&&v.hp>0).map(v=>({v,d:Math.hypot(v.x-u.x,v.y-u.y),angle:Math.abs(norm(Math.atan2(v.y-u.y,v.x-u.x)-u.a))})).filter(t=>t.angle<Math.atan2(input.enabled?.55:.32,t.d)&&visible(u,t.v)).sort((x,y)=>x.d-y.d);if(targets.length){const t=targets[0].v;damage(t,u,a.damage);hit=.15;}}else if(target&&visible(u,target)&&Math.random()<levels[difficulty].accuracy)damage(target,u,a.damage*levels[difficulty].damage);}
function nextStep(u,target){const start=[Math.floor(u.x),Math.floor(u.y)],goal=[Math.floor(target.x),Math.floor(target.y)];const q=[start],visited=new Set([start.join(',')]),prev=new Map();let at=0,found=false;while(at<q.length){const p=q[at++];if(p[0]===goal[0]&&p[1]===goal[1]){found=true;break;}for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const n=[p[0]+dx,p[1]+dy],key=n.join(',');if(!solid(n[0]+.5,n[1]+.5)&&!visited.has(key)){visited.add(key);prev.set(key,p);q.push(n);}}}if(!found)return target;let n=goal;while(prev.has(n.join(','))){const p=prev.get(n.join(','));if(p[0]===start[0]&&p[1]===start[1])break;n=p;}return{x:n[0]+.5,y:n[1]+.5};}
function update(dt){elapsed+=dt;if(elapsed>=180){finish();return;}for(const u of units){if(u.hp<=0){u.dead-=dt;if(u.dead<=0)respawn(u);continue;}u.safe=Math.max(0,u.safe-dt);u.cool=Math.max(0,u.cool-dt);if(u.reload>0){u.reload-=dt;if(u.reload<=0)u.ammo=agents[u.id].mag;}if(u===player){u.a+=input.look;input.look=0;if(input.reload){reload(u);input.reload=false;}const f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown'))+input.y,s=Number(keys.has('KeyD'))-Number(keys.has('KeyA'))+input.x;u.a+=(Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft')))*dt*2.3;const speed=agents[u.id].speed*(keys.has('ShiftLeft')||keys.has('ShiftRight')||input.sprint?1.5:1)*dt/Math.max(1,Math.hypot(f,s));move(u,(Math.cos(u.a)*f-Math.sin(u.a)*s)*speed,(Math.sin(u.a)*f+Math.cos(u.a)*s)*speed);if(f||s)step+=dt*10;if(firing||input.fire||input.fireTap||keys.has('Space'))shoot(u);input.fireTap=false;if(!u.ammo&&!u.reload)reload(u);}else{const targets=units.filter(v=>v!==u&&v.hp>0).sort((a,b)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(b.x-u.x,b.y-u.y));const t=targets[0];if(!t)continue;const can=visible(u,t),d=Math.hypot(t.x-u.x,t.y-u.y);u.a=Math.atan2(t.y-u.y,t.x-u.x);u.think-=dt;if(u.think<=0){u.way=nextStep(u,t);u.think=.35;}if(!can||d>4.5){const dest=can?t:u.way;if(dest){const a=Math.atan2(dest.y-u.y,dest.x-u.x);move(u,Math.cos(a)*dt*levels[difficulty].speed,Math.sin(a)*dt*levels[difficulty].speed);}}if(can&&d<13){if(u.cool<=0){shoot(u,t);u.cool=Math.max(u.cool,.38+Math.random()*.3);}}}if(state!=='playing')break;}flash=Math.max(0,flash-dt);hit=Math.max(0,hit-dt);hurt=Math.max(0,hurt-dt);if(player.hp<=0){input.look=0;input.reload=false;}hudClock-=dt;if(hudClock<=0){hud();hudClock=.1;}}
function hud(){const newScores=[...units].sort((a,b)=>b.score-a.score).map(u=>`<div class="score ${u===player?'me':''}" style="--accent:${agents[u.id].color}"><span>${agents[u.id].name} ${u===player?'· YOU':''}</span><b>${u.score} / 5</b></div>`).join('');if(newScores!==scoreCache){$('scores').innerHTML=newScores;scoreCache=newScores;}$('health').innerHTML=`${Math.ceil(player.hp)} <small>HP</small>`;$('healthfill').style.width=100*player.hp/agents[player.id].hp+'%';$('ammo').innerHTML=`${player.ammo.toString().padStart(2,'0')} <small>/ ∞</small>`;const remain=Math.max(0,Math.ceil(180-elapsed));$('timer').textContent=`${Math.floor(remain/60).toString().padStart(2,'0')}:${(remain%60).toString().padStart(2,'0')}`;$('notice').textContent=player.hp<=0?`${Math.ceil(player.dead)}초 후 재투입`:player.reload>0?`재장전 중 · ${player.reload.toFixed(1)}s`:player.safe>0?'재투입 보호 중':player.ammo===0?'R 키로 재장전':'';$('hit').style.opacity=hit?1:0;$('damage').style.opacity=hurt;}
function finish(){state='finished';input.setActive(false);document.exitPointerLock?.();$('result').hidden=false;const ranked=[...units].sort((a,b)=>b.score-a.score||a.deaths-b.deaths);const tied=ranked.filter(u=>u.score===ranked[0].score&&u.deaths===ranked[0].deaths);$('winner').textContent=tied.length>1?'무승부':ranked[0]===player?'승리를 확보했습니다.':`${agents[ranked[0].id].name} 승리`;$('finalscores').innerHTML=ranked.map(u=>`<div class="score" style="--accent:${agents[u.id].color}"><span>${agents[u.id].name}${u===player?' · YOU':''}</span><b>${u.score} 처치 / ${u.deaths} 데스</b></div>`).join('');firing=false;keys.clear();tone(600,.3,'triangle');}
function robot(color){const c=document.createElement('canvas');c.width=120;c.height=200;const g=c.getContext('2d');g.fillStyle='#0c171e';g.fillRect(28,80,65,75);g.fillStyle=color;g.fillRect(30,73,62,18);g.fillRect(39,30,43,43);g.fillStyle='#20333c';g.fillRect(34,38,54,24);g.fillStyle=color;g.fillRect(40,46,42,7);g.fillStyle='#344650';g.fillRect(24,88,17,53);g.fillRect(82,87,17,50);g.fillRect(37,149,19,43);g.fillRect(66,149,19,43);g.fillStyle='#718789';g.fillRect(45,96,31,27);g.fillStyle='#111c24';g.fillRect(51,116,59,13);g.fillRect(78,122,10,16);g.fillStyle=color;g.fillRect(38,180,17,5);g.fillRect(67,180,17,5);return c;}const sprites=agents.map(a=>robot(a.color));
function polygon(points,fill){ctx.fillStyle=fill;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
function render(){const w=canvas.width,h=canvas.height,view=state==='menu'?{x:10.5,y:17.5,a:-1.7+Math.sin(frame*.002)*.2}:player;if(!view)return;const horizon=h*.46,focal=w*.73;let gradient=ctx.createLinearGradient(0,0,0,horizon);gradient.addColorStop(0,'#10222c');gradient.addColorStop(1,'#789297');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,horizon);gradient=ctx.createLinearGradient(0,horizon,0,h);gradient.addColorStop(0,'#526062');gradient.addColorStop(1,'#17282d');ctx.fillStyle=gradient;ctx.fillRect(0,horizon,w,h);ctx.fillStyle='#d9e9d0';ctx.beginPath();ctx.arc(w*.76,h*.2,29,0,7);ctx.fill();
const stride=2,depth=new Float32Array(Math.ceil(w/stride));for(let x=0;x<w;x+=stride){const offset=Math.atan((x-w/2)/focal),r=ray(view.x,view.y,view.a+offset),d=Math.max(.05,r.d*Math.cos(offset)),wh=Math.min(h*8,focal/d),top=horizon-wh*.57,bottom=top+wh;depth[Math.floor(x/stride)]=d;const colors=r.type===2?[98,119,83]:r.type===3?[54,110,120]:[100,118,123],shade=(r.side?.72:1)*Math.max(.19,1-d/29),seam=(r.uv%1<.035||r.uv%1>.965)?.55:1;ctx.fillStyle=`rgb(${colors.map(c=>Math.round(c*shade*seam)).join(',')})`;ctx.fillRect(x,top,stride,wh);ctx.fillStyle=`rgba(195,224,206,${shade*.25})`;ctx.fillRect(x,top,stride,3);ctx.fillStyle=`rgba(0,0,0,${.15+Math.min(d/50,.4)})`;ctx.fillRect(x,bottom-8,stride,8);ctx.fillStyle=r.type===2?'#b5c88555':'#86c8d344';ctx.fillRect(x,top+wh*.28,stride,wh*.025);if(r.type===1){ctx.fillStyle='#101f2944';ctx.fillRect(x,top+wh*.65,stride,2);}}
if(state!=='menu'){const others=units.filter(u=>u!==player&&u.hp>0).map(u=>{const dx=u.x-view.x,dy=u.y-view.y;return{u,z:dx*Math.cos(view.a)+dy*Math.sin(view.a),side:-dx*Math.sin(view.a)+dy*Math.cos(view.a)};}).sort((a,b)=>b.z-a.z);for(const {u,z,side}of others){if(z<.15)continue;const sh=focal/z*.85,sw=sh*.6,sx=w/2+side/z*focal-sw/2,sy=horizon+focal/z*.43-sh;for(let x=Math.max(0,Math.floor(sx));x<Math.min(w,sx+sw);x++){if(z<depth[Math.floor(x/stride)]+.1)ctx.drawImage(sprites[u.id],(x-sx)/sw*120,0,1,200,x,sy,1,sh);}const center=Math.floor((sx+sw/2)/stride);if(center>=0&&center<depth.length&&z<depth[center]+.1){ctx.textAlign='center';ctx.font='bold 12px sans-serif';ctx.fillStyle=agents[u.id].color;ctx.fillText(agents[u.id].name,sx+sw/2,sy-12);ctx.fillStyle='#08141c';ctx.fillRect(sx,sy-7,sw,3);ctx.fillStyle=agents[u.id].color;ctx.fillRect(sx,sy-7,sw*u.hp/agents[u.id].hp,3);}}
if(player.hp>0){ctx.save();const bob=Math.sin(step)*4,recoil=flash?20:0;ctx.translate(w*.62,h+bob+recoil+(player.reload>0?90:0));const scale=h/750;ctx.scale(scale,scale);polygon([[-68,0],[-53,-130],[10,-160],[90,0]],'#22363d');polygon([[100,0],[70,-130],[135,-118],[208,0]],'#314850');polygon([[-30,0],[-20,-178],[27,-253],[75,-251],[104,-176],[144,0]],'#121f27');polygon([[-20,-178],[27,-253],[35,-207],[6,-119]],'#526770');polygon([[6,-119],[35,-207],[75,-206],[103,-118]],'#30454e');ctx.fillStyle='#0a151d';ctx.fillRect(39,-272,24,104);ctx.fillStyle='#7c9195';ctx.fillRect(42,-276,18,7);ctx.fillStyle=agents[player.id].color;ctx.fillRect(22,-108,65,4);ctx.fillStyle='#0a121b';ctx.fillRect(28,-190,48,12);ctx.fillStyle='#d6f891';ctx.fillRect(48,-188,8,3);if(flash){polygon([[51,-279],[24,-304],[46,-299],[51,-350],[63,-302],[87,-317],[70,-282]],'#ffeaa0');}ctx.restore();}drawMap();}
}
function drawMap(){mini.clearRect(0,0,160,160);for(let y=0;y<20;y++)for(let x=0;x<20;x++)if(grid[y][x]!=='0'){mini.fillStyle='#6a818066';mini.fillRect(x*8,y*8,7,7);}for(const u of units){if(u.hp<=0)continue;mini.fillStyle=agents[u.id].color;mini.beginPath();mini.arc(u.x*8,u.y*8,u===player?3.5:2.5,0,7);mini.fill();if(u===player){mini.strokeStyle=agents[u.id].color;mini.beginPath();mini.moveTo(u.x*8,u.y*8);mini.lineTo(u.x*8+Math.cos(u.a)*10,u.y*8+Math.sin(u.a)*10);mini.stroke();}}}
function loop(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;frame++;if(state==='playing')update(dt);render();requestAnimationFrame(loop);}requestAnimationFrame(loop);
})();
