import {createClient} from '@supabase/supabase-js';

const $=id=>document.getElementById(id),canvas=$('hero-game'),ctx=canvas.getContext('2d'),config=window.parent.TriadOnlineConfig||window.TriadOnlineConfig;

const client=createClient(config.url,config.anonKey,{auth:{persistSession:false,autoRefreshToken:false},realtime:{params:{eventsPerSecond:30}}});

const self=crypto.randomUUID(),MAX_PLAYERS=12,roles=['사업 이사','영업 과장','남원시 9급 공무원'],colors=['#d6f891','#73d9e9','#ffa875'];
let channel=null,matchChannel=null,host='',room='',members=[],running=false,isHost=false,last=0,lastSend=0,keys=new Set(),mouse={x:0,y:0,down:false},heroes=[],enemies=[],bullets=[],seq=0,lastSeq=0,walkSound=0;

const rnd=(n=1)=>Math.random()*n,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

function member(){return members.find(m=>m.id===self)}function status(t){$('hero-status').textContent=t}function send(event,payload){if(channel?.state==='joined')channel.send({type:'broadcast',event,payload:{...payload,from:self}})}
function makeHero(m){return{id:m.id,name:m.name,role:m.role,x:800+rnd(60)-30,y:800+rnd(60)-30,hp:150,a:0,slot:0,grenades:3,cool:0}}function makeEnemy(i){const edge=i%4;
return{id:i,x:edge<2?rnd(1600):edge===2?20:1580,y:edge>=2?rnd(1600):edge?20:1580,hp:70,cool:rnd(1),a:0}}
function start(){running=true;
$('hero-menu').hidden=true;
$('hero-hud').hidden=false;
heroes=members.map(makeHero);
enemies=Array.from({length:50},(_,i)=>makeEnemy(i));
bullets=[];
}
function audioSlash(){try{const a=audioSlash.ctx||=new AudioContext(),o=a.createOscillator(),g=a.createGain();
o.type='sawtooth';
o.frequency.setValueAtTime(900,a.currentTime);
o.frequency.exponentialRampToValueAtTime(150,a.currentTime+.09);
g.gain.setValueAtTime(.035,a.currentTime);
g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.1);
o.connect(g).connect(a.destination);
o.start();
o.stop(a.currentTime+.1)}catch{}}
function attack(h){if(h.cool>0)return;
if(h.slot===0){h.cool=.16;
bullets.push({x:h.x,y:h.y,a:h.a,owner:h.id,left:520});
}else if(h.slot===1&&h.grenades){h.cool=.7;
h.grenades--;
const x=h.x+Math.cos(h.a)*130,y=h.y+Math.sin(h.a)*130;
for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-x,e.y-y)<95)e.hp-=65;
}else if(h.slot===2){h.cool=.38;
audioSlash();
for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-h.x,e.y-h.y)<55&&Math.abs(Math.atan2(Math.sin(Math.atan2(e.y-h.y,e.x-h.x)-h.a),Math.cos(Math.atan2(e.y-h.y,e.x-h.x)-h.a)))<.8)e.hp-=48;
}}
function sim(dt){for(const h of heroes)h.cool=Math.max(0,h.cool-dt);
for(const e of enemies){if(e.hp<=0)continue;
let target=heroes.filter(h=>h.hp>0).sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y))[0];
if(!target)continue;
e.a=Math.atan2(target.y-e.y,target.x-e.x);
const d=Math.hypot(target.x-e.x,target.y-e.y);
if(d>150){e.x+=Math.cos(e.a)*32*dt;
e.y+=Math.sin(e.a)*32*dt;
}e.cool-=dt;
if(d<310&&e.cool<=0){e.cool=.7+rnd(.6);
bullets.push({x:e.x,y:e.y,a:e.a,owner:'ai',left:350});
}}
for(let i=bullets.length-1;
i>=0;
i--){const b=bullets[i];
b.x+=Math.cos(b.a)*500*dt;
b.y+=Math.sin(b.a)*500*dt;
b.left-=500*dt;
let hit=false;
if(b.owner==='ai'){const h=heroes.find(h=>h.hp>0&&Math.hypot(h.x-b.x,h.y-b.y)<13);
if(h){h.hp-=12;
hit=true;
}}else{const e=enemies.find(e=>e.hp>0&&Math.hypot(e.x-b.x,e.y-b.y)<13);
if(e){e.hp-=25;
hit=true;
}}if(hit||b.left<=0)bullets.splice(i,1);
}if(!enemies.some(e=>e.hp>0)||!heroes.some(h=>h.hp>0)){running=false;
$('hero-result').hidden=false;
$('hero-result h2').textContent=enemies.some(e=>e.hp>0)?'영웅 전멸':'AI 50명 섬멸 완료';
}}
function local(dt){const me=heroes.find(h=>h.id===self);
if(!me||me.hp<=0)return;
const x=Number(keys.has('KeyD'))-Number(keys.has('KeyA')),y=Number(keys.has('KeyS'))-Number(keys.has('KeyW')),l=Math.max(1,Math.hypot(x,y));
me.x=clamp(me.x+x/l*110*dt,10,1590);
me.y=clamp(me.y+y/l*110*dt,10,1590);
me.a=Math.atan2(mouse.y-me.y,mouse.x-me.x);
if((x||y)&&me.slot===2){walkSound-=dt;
if(walkSound<=0){walkSound=.32;
audioSlash();
}}if(mouse.down)attack(me);
return{x:me.x,y:me.y,a:me.a,slot:me.slot,fire:mouse.down};
}
function draw(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);
canvas.width=r.width*d;
canvas.height=r.height*d;
ctx.setTransform(d,0,0,d,0,0);
ctx.fillStyle='#243d31';
ctx.fillRect(0,0,r.width,r.height);
const me=heroes.find(h=>h.id===self)||{x:800,y:800};
const sc=Math.min(r.width/900,r.height/900),ox=r.width/2-me.x*sc,oy=r.height/2-me.y*sc;
ctx.save();
ctx.translate(ox,oy);
ctx.scale(sc,sc);
ctx.strokeStyle='#87977f';
ctx.lineWidth=8;
ctx.strokeRect(0,0,1600,1600);
for(let i=120;
i<1500;
i+=220){ctx.fillStyle='#526358';
ctx.fillRect(i,(i*1.7)%1300+80,90,65);
}for(const b of bullets){ctx.fillStyle='#fff2a5';
ctx.fillRect(b.x-3,b.y-3,6,6)}for(const e of enemies)if(e.hp>0){ctx.fillStyle='#df6d5e';
ctx.beginPath();
ctx.arc(e.x,e.y,11,0,7);
ctx.fill()}for(const h of heroes)if(h.hp>0){ctx.fillStyle=colors[h.role];
ctx.beginPath();
ctx.arc(h.x,h.y,14,0,7);
ctx.fill();
ctx.fillStyle='#fff';
ctx.font='18px sans-serif';
ctx.fillText(h.name,h.x-22,h.y-22)}ctx.restore();
const h=heroes.find(h=>h.id===self);
if(h){$('hero-alive').textContent='AI '+enemies.filter(e=>e.hp>0).length+' / 50';
$('hero-hp').textContent='HP '+Math.max(0,h.hp);
$('hero-weapon').textContent=['총','수류탄 '+h.grenades+'/3','칼'][h.slot];
}}
function frame(t){const dt=Math.min(.05,(t-last)/1000);
last=t;
if(running){const input=local(dt);
if(isHost)sim(dt);
else if(input&&t-lastSend>50){lastSend=t;
send('input',{input})}if(isHost&&t-lastSend>66){lastSend=t;
send('state',{seq:++seq,heroes,enemies,bullets})}}draw();
requestAnimationFrame(frame)}requestAnimationFrame(frame);

function connect(create,url,publicMatch=false){let q;
try{q=create&&!publicMatch?null:new URL(url).searchParams}catch{return status('올바른 초대 URL을 입력하세요.')}room=create&&!publicMatch?crypto.randomUUID():q.get('heroRoom');
host=create&&!publicMatch?self:q.get('heroHost');
if(!room||!host)return status('올바른 초대 URL을 입력하세요.');
isHost=host===self;
members=isHost?[{id:self,name:$('hero-name').value||'영웅',role:+$('hero-role').value}]:[];
channel=client.channel('triad-hero:'+room,{config:{broadcast:{self:false},presence:{key:self}}});

channel.on('broadcast',{event:'hello'},({payload:p})=>{if(!isHost||running||members.length>=MAX_PLAYERS)return;
members.push({id:p.from,name:String(p.name||'영웅').slice(0,12),role:clamp(+p.role||0,0,2)});
send('roster',{members});
status('영웅 '+members.length+'/'+MAX_PLAYERS+' 접속')});
channel.on('broadcast',{event:'roster'},({payload:p})=>{if(!isHost&&p.from===host&&Array.isArray(p.members)){members=p.members;
status('영웅 '+members.length+'/'+MAX_PLAYERS+' · 방장 시작 대기')}});
channel.on('broadcast',{event:'start'},({payload:p})=>{if(p.from===host){members=p.members;
start()}});
channel.on('broadcast',{event:'input'},({payload:p})=>{if(!isHost)return;
const h=heroes.find(h=>h.id===p.from),i=p.input;
if(h&&i){h.x=clamp(+i.x,0,1600);
h.y=clamp(+i.y,0,1600);
h.a=+i.a||0;
h.slot=clamp(+i.slot||0,0,2);
if(i.fire)attack(h)}});
channel.on('broadcast',{event:'state'},({payload:p})=>{if(isHost||p.from!==host||p.seq<=lastSeq)return;
lastSeq=p.seq;
heroes=p.heroes;
enemies=p.enemies;
bullets=p.bullets;
if(!$('hero-menu').hidden)start()});
channel.subscribe(async s=>{if(s!=='SUBSCRIBED')return;
await channel.track({online:true});
if(isHost){const u=new URL(location.href);
u.search=new URLSearchParams({heroRoom:room,heroHost:host});
$('hero-invite').value=u.href;
$('hero-copy').hidden=$('hero-launch').hidden=false;
status((publicMatch?'공개 매칭방 준비 · ':'초대 URL 생성 완료 · ')+'현재 1/'+MAX_PLAYERS);if(publicMatch)setTimeout(()=>{if(isHost&&!running){send('start',{members});start()}},10000)}else send('hello',{name:$('hero-name').value,role:+$('hero-role').value})});
}
$('hero-public').onclick=async()=>{if(matchChannel||channel)return;
 status('공개 대기열 접속 중…');
 const profile={id:self,name:($('hero-name').value||'영웅').slice(0,12),role:+$('hero-role').value,joined:Date.now()};
 matchChannel=client.channel('triad-hero-public-v1',{config:{presence:{key:self}}});
 matchChannel.on('presence',{event:'sync'},()=>{if(channel)return;
  const waiting=Object.values(matchChannel.presenceState()).flat().filter(v=>v?.id&&Number.isFinite(v.joined)).sort((a,b)=>a.joined-b.joined||a.id.localeCompare(b.id));
  const index=waiting.findIndex(v=>v.id===self);if(index<0)return;
  const offset=Math.floor(index/MAX_PLAYERS)*MAX_PLAYERS,group=waiting.slice(offset,offset+MAX_PLAYERS),leader=group[0];
  status(`공개 대기열 ${index+1}번 · ${group.length}/${MAX_PLAYERS}`);
  const joinBatch=()=>{if(channel)return;const u=new URL(location.href);u.search=new URLSearchParams({heroRoom:'public-'+leader.id,heroHost:leader.id});connect(leader.id===self,u.href,true);};
  if(group.length>=2||Date.now()-leader.joined>12000)joinBatch();else setTimeout(joinBatch,Math.max(250,12000-(Date.now()-leader.joined)));
 });
 await matchChannel.subscribe(async s=>{if(s==='SUBSCRIBED')await matchChannel.track(profile)});
};
$('hero-solo').onclick=()=>{members=[{id:self,name:$('hero-name').value||'고영훈',role:+$('hero-role').value}];
isHost=true;
start()};
$('hero-create').onclick=()=>connect(true);
$('hero-join').onclick=()=>connect(false,$('hero-invite').value);
$('hero-launch').onclick=()=>{if(isHost){send('start',{members});
start()}};
$('hero-copy').onclick=async()=>{await navigator.clipboard.writeText($('hero-invite').value);
status('새 초대 URL을 복사했습니다.')};
$('hero-switch').onclick=()=>{const h=heroes.find(h=>h.id===self);
if(h)h.slot=(h.slot+1)%3};
addEventListener('wheel',e=>{const h=heroes.find(h=>h.id===self);
if(h)h.slot=(h.slot+(e.deltaY>0?1:2))%3},{passive:true});
addEventListener('keydown',e=>keys.add(e.code));
addEventListener('keyup',e=>keys.delete(e.code));
canvas.onmousemove=e=>{const r=canvas.getBoundingClientRect(),me=heroes.find(h=>h.id===self);
if(me){const sc=Math.min(r.width/900,r.height/900);
mouse.x=me.x+(e.clientX-r.left-r.width/2)/sc;
mouse.y=me.y+(e.clientY-r.top-r.height/2)/sc}};
canvas.onmousedown=()=>mouse.down=true;
addEventListener('mouseup',()=>mouse.down=false);
const q=new URL(location.href).searchParams;
if(q.has('heroRoom')){$('hero-invite').value=location.href;
status('이름과 영웅을 정한 뒤 초대 URL로 접속하세요.')}
