(()=>{'use strict';const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d'),mini=$('minimap').getContext('2d');let game=new RoyaleCore.Royale(),started=false,paused=false,seenDeath=false,last=0,scale=1,ox=0,oy=0;const keys=new Set(),control={x:0,y:0,angle:0,fire:false};
function clear(){keys.clear();control.x=control.y=0;control.fire=false;}
function start(){game=new RoyaleCore.Royale();started=true;paused=false;seenDeath=false;clear();$('result-br').hidden=true;$('pause-br').textContent='일시정지';}
$('new-br').onclick=$('retry-br').onclick=start;$('watch-br').onclick=()=>{$('result-br').hidden=true;};$('pause-br').onclick=()=>{paused=!paused;clear();$('pause-br').textContent=paused?'계속하기':'일시정지';};
addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyR','KeyF','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(started&&!paused&&game.time>=5&&!e.repeat&&e.code==='KeyF')game.heal(game.players[0]);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{clear();if(started){paused=true;$('pause-br').textContent='계속하기';}});document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();paused=true;$('pause-br').textContent='계속하기';}});
function aim(e){const r=canvas.getBoundingClientRect();const x=(e.clientX-r.left-ox)/scale,y=(e.clientY-r.top-oy)/scale;control.angle=Math.atan2(y-game.players[0].y,x-game.players[0].x);}
canvas.onpointerdown=e=>{aim(e);control.fire=true;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=aim;canvas.onpointerup=canvas.onpointercancel=()=>control.fire=false;
const pad=$('pad');function steer(e){const r=pad.getBoundingClientRect();control.x=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/35));control.y=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/35));}pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);steer(e);};pad.onpointermove=e=>{if(pad.hasPointerCapture(e.pointerId))steer(e);};pad.onpointerup=pad.onpointercancel=()=>{control.x=control.y=0;};$('heal-br').onclick=()=>{if(started&&!paused&&game.time>=5)game.heal(game.players[0]);};$('reload-br').onclick=()=>{if(started&&!paused&&game.time>=5)game.reload(game.players[0]);};
function circle(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}
function render(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#122b30';ctx.fillRect(0,0,r.width,r.height);scale=Math.min(r.width,r.height)/1000;ox=(r.width-1000*scale)/2;oy=(r.height-1000*scale)/2;ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.save();ctx.beginPath();ctx.rect(0,0,1000,1000);ctx.clip();ctx.fillStyle='#344d3c';ctx.fillRect(0,0,1000,1000);ctx.strokeStyle='#ffffff09';ctx.lineWidth=1;for(let i=0;i<=1000;i+=50){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,1000);ctx.moveTo(0,i);ctx.lineTo(1000,i);ctx.stroke();}
for(const o of game.obstacles){ctx.fillStyle='#172b24';ctx.fillRect(o.x+5,o.y+5,o.w,o.h);ctx.fillStyle='#71806a';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#96a088';ctx.strokeRect(o.x+4,o.y+4,o.w-8,o.h-8);}
for(const item of game.items){ctx.fillStyle=RoyaleCore.weapons[item.kind]?'#efc965':item.kind==='med'?'#e99191':'#9fc8e5';ctx.fillRect(item.x-3,item.y-3,6,6);}
ctx.save();ctx.beginPath();ctx.rect(0,0,1000,1000);ctx.arc(500,500,game.zone.r,0,Math.PI*2,true);ctx.fillStyle='#536cec66';ctx.fill('evenodd');ctx.restore();ctx.strokeStyle='#bbd3ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(500,500,game.zone.r,0,Math.PI*2);ctx.stroke();
for(const p of game.players){if(p.hp<=0)continue;circle(ctx,p.x,p.y,p.id===0?8:6,p.id===0?'#e0ffa6':'#efab8f');ctx.strokeStyle=p.id===0?'#fff':'#352d28';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+Math.cos(p.angle)*12,p.y+Math.sin(p.angle)*12);ctx.stroke();if(game.time<5){ctx.strokeStyle='#e8efde';ctx.beginPath();ctx.arc(p.x,p.y-10,14,Math.PI,0);ctx.stroke();}if(p.id===0){ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.fillText('YOU',p.x-15,p.y-17);}}
for(const b of game.bullets)circle(ctx,b.x,b.y,2,'#ffecab');ctx.restore();const p=game.players[0],alive=game.players.filter(p=>p.hp>0).length;
$('status').textContent=`${paused?'일시정지 · ':''}${!started?'출격 대기':game.time<5?'낙하 중 '+Math.ceil(5-game.time)+'초':'생존 '+alive+' / 100'} · ${Math.floor(game.time/60)}:${Math.floor(game.time%60).toString().padStart(2,'0')} | 안전 반경 ${Math.round(game.zone.r)}m | 처치 ${game.kills}`;
$('inventory').textContent=`HP ${Math.ceil(p.hp)} · 방어구 ${Math.ceil(p.armor)} | ${p.weapon?RoyaleCore.weapons[p.weapon].name:'무기 없음 — 노란 아이템 수집'} · ${p.ammo}/${p.reserve} ${p.reloading?'재장전 중':''} | 치료 ${p.meds}`;
mini.fillStyle='#233d31';mini.fillRect(0,0,180,180);mini.strokeStyle='#a9c6ff';mini.beginPath();mini.arc(90,90,game.zone.r*.18,0,Math.PI*2);mini.stroke();circle(mini,p.x*.18,p.y*.18,3,'#ddff9d');
if(started&&((p.hp<=0&&!seenDeath)||game.over&&!seenDeath)){seenDeath=true;$('result-br').hidden=false;$('result-title').textContent=game.winner===0?'WINNER · 최후의 생존자':game.over&&game.winner===null?'생존자 없음':'전투 종료';$('result-copy').textContent=`${game.rank||alive}위 / 100 · ${game.kills} 처치${!game.over?' · 전장 보기로 AI 경기 관전':''}`;}
}
function frame(t){const dt=Math.min((t-last)/1000,.05);last=t;if(started&&!paused){game.step(dt,{...control,x:control.x+Number(keys.has('KeyD'))-Number(keys.has('KeyA')),y:control.y+Number(keys.has('KeyS'))-Number(keys.has('KeyW')),reload:keys.has('KeyR')});}render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
